#!/usr/bin/expect
set host [lindex $argv 0]
set port [lindex $argv 1]
if {[string match "*gpon*" $host]} {
set currentlogin "huawei"
set currentpass "pass"
} elseif {[string match "*gepon*" $host]} {
set currentlogin "admin"
set currentpass "password"
} else {
set currentlogin "taclogin"
set currentpass "tacpass"
}
if {$port == ""} {
spawn telnet $host
} else {
spawn telnet $host $port
}
expect {
"User" { send "$currentlogin\r" }
"login" { send "$currentlogin\r" }
}
expect "ord:"
send "$currentpass\radmin\radmin\renable\rFDjn{eqDfv15\r"
send "en ad\r\r"
interact
exit 0
